set ruler
set ignorecase
set hlsearch
set incsearch
set tabstop=4
set shiftwidth=4
set smarttab
set autoindent
set smartindent
set expandtab
set number
set numberwidth=4
set tw=100
set colorcolumn=101

syntax on
colorscheme monokai

autocmd BufRead,BufNewFile *.md setlocal textwidth=100
" Add ctrl+backspace to remove word backwards in normal, insert and command modes
nnoremap <C-H> db
inoremap <C-H> <C-W>
cnoremap <C-H> <C-W>

" The below config changes cursor to wrap to next line after EOL.
" The inoremap commands are to have the same effect in insert mode as well.
" set whichwrap+=<,>,h,l
" inoremap <Left> <C-o>h
" inoremap <Right> <C-o>l
" inoremap <Up> <C-o>k
" inoremap <Down> <C-o>j

