---
tooling_reversing_packages:
  - openjdk-21-jdk
  - unzip
  - xz-utils

tooling_reversing_github_api_headers:
  Accept: application/vnd.github+json
  X-GitHub-Api-Version: '2022-11-28'

tooling_reversing_ghidra_release_api: https://api.github.com/repos/NationalSecurityAgency/ghidra/releases/latest
tooling_reversing_binary_ninja_release_api: https://api.github.com/repos/Vector35/binaryninja-api/releases/latest
tooling_reversing_radare2_release_api: https://api.github.com/repos/radareorg/radare2/releases/latest
